### ISSUE TITLE
Where to announce news and breaking changes

### ISSUE THREAD

**Issue by kobalicek** [kobalicek/asmjit#116]
After the project has moved from google code to github I also stopped using google groups, which worked as a mailing list. Since asmjit has its users I really wonder where to announce news about the project and breaking changes, which happen and will happen before the 1.0 release.

I was thinking about twitter, but no idea.

**Comment by nelson2005** [comment]
It seems like everyone watching the project will get an email if you post it here, right?
On Dec 4, 2015 7:46 PM, Petr Kobalicek <notifications@github.com> wrote:After the project has moved from google code to github I also stopped using google groups, which worked as a mailing list. Since asmjit has its users I really wonder where to announce news about the project and breaking changes, which happen and will happen before the 1.0 release.

I was thinking about twitter, but no idea.

**Comment by yzrmn** [comment]
You could set up a wiki page for breaking changes, just a thought...

**Comment by kobalicek** [comment]
Yeah I guess CHANGELOG.md would be a good start.

**Comment by kobalicek** [comment]
Ok, so for now there is a new BREAKING.md page that will be updated with breaking changes.
