### ISSUE TITLE
Compiler get current offset?

### ISSUE THREAD

**Issue by feliwir** [kobalicek/asmjit#120]
Hello everyone,
i wanted to ask if it's possible to the current offset in the instructionstream somehow? Here is my use-case: http://www.angelcode.com/angelscript/sdk/docs/manual/doc_adv_jit.html 
When generating the jit-code i need to specify the position where the function will jump in later. See here:
```cpp
int Compiler::CompileFunction(asIScriptFunction *function, asJITFunction *output)
	{		
		asUINT   length;
		asDWORD *byteCode = function->GetByteCode(&length);
		if (byteCode == 0 || length == 0)
		{
			output = 0;
			return 1;
		}
		asDWORD *end = byteCode + length;
		X86Assembler a(&m_private->runtime);
		X86Compiler c(&a);

		//JITCODE STARTS HERE
		c.addFunc(asmjit::FuncBuilder2<void, asSVMRegisters*, asPWORD>(kCallConvHost));
		X86GpVar regs = c.newIntPtr("regs");
		X86GpVar arg = c.newUIntPtr("arg");
		c.setArg(0, regs);
		c.setArg(1, arg);
		//WE SPECIFY ARG later
		c.jmp(arg);

		while (byteCode < end)
		{
			// Determine the instruction
			asEBCInstr op = asEBCInstr(*(asBYTE*)byteCode);
			switch (op)
			{
			case asBC_SUSPEND:
				break;
			case asBC_JitEntry:
				//THIS WILL BE arg later
				asBC_PTRARG(byteCode) = c.getOffset()//??This does not exist;
				break;
			}

			// Move to next instruction
			byteCode += asBCTypeSize[asBCInfo[op].type];
		}

		c.ret();

		c.endFunc();
		//JITCODE ENDS HERE

		c.finalize();

		void* funcPtr = a.make();
		*output = asmjit_cast<asJITFunction>(funcPtr);
		
		return 0;
	}
```

I tried to use labels aswell, but i don't know how to pass asmjit labels as parameters unfortunaly

**Comment by kobalicek** [comment]
Well, you cannot really jump to an arbitrary location (specified by a register) when using Compiler (well, you can, there is one use-case atm), for this you have to use Assembler anyway. If the location can be specified as a Label you can use Label instead.

BTW it's possible to get an offset of a bound Label that has been assembled, no matter how the label has been created (Assembler / Compiler), maybe that can help?

Or maybe I just don't see what you are trying to accomplish here, can you please elaborate a bit more?

**Comment by feliwir** [comment]
Hello, thanks for your quick response. I tried to mix assembler and compiler now to get the label offset after assembling:
```cpp
int Compiler::CompileFunction(asIScriptFunction *function, asJITFunction *output)
	{
		asUINT   length;
		asDWORD *byteCode = function->GetByteCode(&length);
		if (byteCode == 0 || length == 0)
		{
			output = 0;
			return 1;
		}
		asDWORD *end = byteCode + length;
		X86Assembler a(&m_private->runtime);
		X86Compiler c(&a);
		
		//JITCODE STARTS HERE
		c.addFunc(asmjit::FuncBuilder2<void, asSVMRegisters*, asPWORD>(kCallConvHost));
		X86GpVar regs = c.newIntPtr("regs");
		X86GpVar arg = c.newUIntPtr("arg");
		c.setArg(0, regs);
		c.setArg(1, arg);
		//WE SPECIFY ARG later
		c.jmp(arg);
		std::vector<Label> entries;
		std::vector<asDWORD *> entry_offset;

		while (byteCode < end)
		{
			// Determine the instruction
			asEBCInstr op = asEBCInstr(*(asBYTE*)byteCode);
			switch (op)
			{
			case asBC_SUSPEND:
				break;
			case asBC_JitEntry:
				//THIS WILL BE arg later
				entry_offset.push_back(byteCode);
				const auto& label = c.newLabel();
				c.bind(label);
				entries.push_back(label);
				
				break;
			}

			// Move to next instruction
			byteCode += asBCTypeSize[asBCInfo[op].type];
		}

		c.ret();

		c.endFunc();
		//JITCODE ENDS HERE

		c.finalize();

		//Get label offsets
		int n = 0;
		for (const auto& entry : entries)
		{
			auto offset = a.getLabelOffset(entry);
			asBC_PTRARG(entry_offset[n]) = offset;
			++n;
		}

		void* funcPtr = a.make();
		*output = asmjit_cast<asJITFunction>(funcPtr);

		return 0;
	}
```

Problem with this is that a.getLabelOffset keeps returning -1 eventhough the label got bound by the compiler. What is wrong with this?

**Comment by kobalicek** [comment]
The only reason for `Label` not being reported is that Compiler removed it. But that would be a bug as `Compiler` is permitted to remove instructions, but not labels and data. The`Compiler::finalize()` function serializes all instructions to `Assembler`, so after that you should be able to get Label offsets as well.

I think it would be worth to better describe the core problem and to create a test-case and report a simplified code that I can compile & run. I would help me to better understand what you are trying to do. Because I really don't understand the current code. I mean it basically jumps somewhere and then you add Labels in purpose to read their addresses, but if I look at it all labels will have the same address anyway (label is just a placeholder, it doesn't encode to anything in the final assembly). Maybe I can help with the solution if I know a bit more details?

**Comment by feliwir** [comment]
The core problem here is the following: I want a jit compiled function where with multiple entry points -> the function can jump to a specific adress/label that is specified by an argument somehow. This behaviour should work with code pasted above, but it doesn't

**Comment by kobalicek** [comment]
I checked the AngelScript documentation and my conclusion is that you cannot use `X86Compiler` for that. You have to use `X86Assembler` for implementing that kind of JIT, as it requires JIT code to be easily suspendable and resumable. This is not possible with `X86Compiler` as it manages registers by itself. I would recommend you to look at `V8` engine and their `MacroAssembler` class to see how other JIT compilers extend basic assembler implementations with other building blocks. I think it's possible to do with pure asmjit, but extending X86Assembler may be worth it, and don't hesitate to ask for some functionality you will need if you start so.

What you have to do is basically the following:

  1. Prolog - do what AS wants, move VM regs into real regs
  2. Jump to the position it wants, this can be implemented as a jump table - you create a label for every bytecode entry you compile and push that label somewhere - the jump table can be then emitted after the function `ret`. I don't know how this is supposed to work and when VM can suspend and resume the JIT function (I guess it would be only a few places, but it's not clear to me).
  3. Compile each byte-code instruction
  4. Epilog - move real regs to VM regs. Epilog will be used also to suspend the execution I guess.

Well it would be much easier to do if you can actually look at some AS JIT implementation, because the doc is very brief and doesn't go into detail.

**Comment by feliwir** [comment]
Thanks very much, that helped a lot :) i have an existing jit :)

**Comment by kobalicek** [comment]
I'm closing this
